/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.snn_simulator.desktop;

import romanow.snn_simulator.fft.FFT;

/**
 *
 * @author romanow
 */
public abstract class LayerWindow extends javax.swing.JFrame implements I_SpectrumWindow{
    LayerWindowCallBack back=null;
    private boolean white=false;
    /**
     * Creates new form NeuronLayerWindow
     */
    public LayerWindow(String title) {
        this(0,title,540,0,0,false);
        }
    public LayerWindow(int num,String title, int hight, int dx, int dy, boolean white) {
        initComponents();
        this.white = white;
        setTitle(title);
        this.setBounds(30+num*20, 200+num*20, 1080+dx, hight+dy);
        setVisible(true);
        this.toFront();
        }
    public void reset(){
        }
    public void paint(float spikes[], int subToneCount){
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (back!=null)
            back.release(this);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(FFT fft) {
        }

    @Override
    public void setCallBack(LayerWindowCallBack back) {
        this.back = back; 
        }
    @Override
    public void paint(float[] val, String title) {}

    @Override
    public void paint(float[] val) {}
}
